Activity/Activity/Controllers/HomeController.cs
using Activity.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;

namespace Activity.Controllers
{
    public class HomeController : Controller
    {
        private ActivityEntities db = new ActivityEntities();
        public ActionResult Index()
        {
            
            TempData["EndTime"] = Session["EndTime"];
          
            return View();
        }

        [HttpPost]
        public void PostCountdownTimer()
        {
            if (Session["EndTime"] == null)
            {
                Session["EndTime"] = DateTime.Now.AddHours(0).AddMinutes(00).AddSeconds(30).ToString("dd-MM-yyyy h:mm:ss tt");
            }
            TempData["EndTime"] = Session["EndTime"];
           
            Response.Redirect("/Home/Index");
        }

        // Destroys EndTime Session object
        public void StopTimer()
        {
            Session.Abandon();
        }
        public ActionResult StartGame()

        {
            var idList = db.Words.Select(x => x.WordsID).OrderBy(y => Guid.NewGuid()).ToList();
          

            if (idList.Count == 0)
            {
                return RedirectToAction("Finish");
            }
            Word word = db.Words.Find(idList[0]);



            db.Words.Remove(word);
            db.SaveChanges();



            return View(word);
        }

        public ActionResult Finish()
        {
            return View();
        }

    }
}

Activity/Activity/Controllers/StartGameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;

namespace Activity.Controllers
{
    public class StartGameController : Controller
    {
        private ActivityEntities db = new ActivityEntities();

       
       
        
        // GET: StartGame/StartGame/5
        public ActionResult StartGame()

        {
            var idList = db.Words.Select(x => x.WordsID).OrderBy(y => Guid.NewGuid()).ToList();

            if (idList.Count==0)
            {
                return RedirectToAction("Finish");
            }
            Word word = db.Words.Find(idList[0]);
           
            
            
               db.Words.Remove(word);
            db.SaveChanges();

           

            return View(word);
        }

        public ActionResult Finish()
        {
            return View();
        }


        // GET: StartGame/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Word word = db.Words.Find(id);
            if (word == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "PlayerName", word.PlayerID);
            return View(word);
        }

        // POST: StartGame/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WordsID,Word1,PlayerID")] Word word)
        {
            if (ModelState.IsValid)
            {
                db.Entry(word).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "PlayerName", word.PlayerID);
            return View(word);
        }

        // GET: StartGame/Delete/5
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Activity/Activity/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Activity/Activity/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Activity/Activity/Views/Home/Index.cshtml
@model Data.Word

@{
    ViewBag.Title = "Home Page";

}


<div>
    <h4>Word</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Word1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Word1)
        </dd>



    </dl>

</div>


<p>
    @Html.ActionLink("Next", "Index")
</p>

Activity/Activity/Views/Home/StartGame.cshtml
@model Data.Word

<div>
    <h4>Word</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Word1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Word1)
        </dd>



    </dl>

</div>


<p>
    @Html.ActionLink("Next", "StartGame")
</p>